--- #YAML:1.0
name:               Data-Tools
version:            1.06
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:
        type:  git
        url:   https://github.com/cade-vs/perl-data-tools.git
        web:   https://github.com/cade-vs/perl-data-tools
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  2
